api_platform:
    # http_cache:
    #     invalidation:
    #         enabled: true
    #         varnish_urls: ['%env(VARNISH_URL)%']
    #     public: true
    # defaults:
    #     cache_headers:
    #         max_age: 0
    #         shared_max_age: 3600
    #         vary: ['Content-Type', 'Authorization', 'Origin']
    # eager_loading:
    #     max_joins: 100
    mapping:
        paths: ['%kernel.project_dir%/src/Entity']
    patch_formats:
        json: ['application/merge-patch+json']
    formats:
        json: ['application/json']
        html: ['text/html']
    swagger:
        versions: [3]
