# see https://symfony.com/doc/current/reference/configuration/framework.html
framework:
    trusted_hosts:
        - 'localhost'
        - '127.0.0.1'
        - 'edith.bredon'
        - 'backoffice.edithbredon'
        - 'backoffice2.edithbredon'

    secret: '%env(APP_SECRET)%'
    http_method_override: false
    translator: 
        fallbacks: '%locale%'
        default_path: '%kernel.project_dir%/translations'
        enabled: true
    enabled_locales: ['fr', 'en']
    default_locale: fr
    serializer:
        default_context:
            enable_max_depth: true
            name_converter: 'serializer.name_converter.camel_case_to_snake_case'
        
    #csrf_protection: true
    # MAX connections to the database
    # https://symfony.com/doc/current/reference/configuration/framework.html#default-database-table-options
    handle_all_throwables: false
    http_cache: 
        enabled: true
        trace_level: 'none'
        default_ttl: 0
        allow_reload: true
        allow_revalidate: true
    http_client:
        max_host_connections: 6 # default value
        scoped_clients: ~ # to define a client for a specific host

    # Enables session support. Note that the session will ONLY be started if you read or write from it.
    # Remove or comment this section to explicitly disable session support.
    session:
        handler_id: 'session.handler.native_file'
        save_path: '%kernel.project_dir%/var/sessions/%kernel.environment%'
        cookie_secure: auto
        cookie_samesite: lax
        storage_factory_id: session.storage.factory.native

    #esi: true
    #fragments: true
    php_errors:
        log: true

when@test:
    framework:
        test: ~ # Enables the test pack
        session:
            storage_factory_id: session.storage.factory.mock_file
