nelmio_cors:
        defaults:
            allow_credentials: false
            allow_origin: ['%env(CORS_ALLOW_ORIGIN)%']
            allow_methods: ['GET', 'OPTIONS', 'POST', 'PUT', 'PATCH', 'DELETE']
            allow_headers: ['Content-Type', 'Authorization']
            expose_headers: ['Link']
            max_age: 3600
            hosts: []
            origin_regex: false
            forced_allow_origin_value: ~
        paths:
            '^/api/*':
                allow_origin: ['https://edithbredon.fr']
                allow_headers: ['Content-Type', 'Authorization', 'X-Requested-With', 'Accept', 'Origin', 'Cache-Control', 'HTTP/1.1 200 OK']
                allow_methods: ['POST', 'OPTIONS', 'PUT', 'GET', 'DELETE']
                max_age: 3600
            '^/':
                origin_regex: true
                allow_origin: ['https://edithbredon.fr']
                allow_headers: ['Content-Type', 'Authorization', 'X-Requested-With', 'Accept', 'Origin', 'Cache-Control', 'HTTP/1.1 200 OK']
                allow_methods: ['POST', 'PUT', 'GET', 'DELETE']
                max_age: 3600
                hosts: ['^api\.']
