twig:
    default_path: '%kernel.project_dir%/templates'
    debug: '%kernel.debug%'

    globals:
        gg_recaptcha_site_key: '%env(GOOGLE_RECAPTCHA_SITE_KEY)%'
        decodeHtmlEntities: 'App\Twig\AppExtension\decodeHtmlEntities'
        truncate: 'App\Twig\AppExtension\truncate'
        locale: '%locale%'

    form_themes:
        - 'bootstrap_5_layout.html.twig'

when@test:
    twig:
        strict_variables: true
