vich_uploader:
    db_driver: orm
    metadata:
        type: attribute

    mappings:
        project_images:
            uri_prefix: /images/project
            upload_destination: '%kernel.project_dir%/public/images/project'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
            inject_on_load: false
            delete_on_update: true
            delete_on_remove: true
        