controllers:
    resource: ../src/Controller/
    type: attribute

kernel:
    resource: ../src/Kernel.php
    type: annotation

# Resource "App\Entity\Language" not found in . (which is being imported from "D:\Documents\backoffice\config/routes/api_platform.yaml")


# https://api-platform.com/docs/core/operations/
# api/config/routes.yaml
# book_post_publication:
#     path: /books/{id}/publication
#     methods: ['POST']
#     defaults:
#         _controller: App\Controller\BookController::createPublication
#         _api_resource_class: App\Entity\Book
#         _api_operation_name: post_publication
