# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices.html#use-parameters-for-application-configuration
parameters:
    locale: 'fr'
    translator:
        fallbacks: ['fr']
    upload_directory: '%kernel.project_dir%/public/uploads'
    default_admin_email: contact@edithbredon.fr

services:
    # default configuration for services in *this* file
    App\Service\FileUploader:
        arguments:
            $targetDirectory: '%upload_directory%'
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.
        # bind:
        #     bool true: true
        #     $formLoginAuthenticator:
        #         class: App\Security\LoginFormAuthenticator
        #         arguments:
        #             $userProvider: app_user_provider
                    # $isDebug: $isDebug

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../Migrations/'
            - '../Tests/'
            - '../src/Kernel.php'
    App\Controller\:
        resource: '../src/Controller'
        tags: ['controller.service_arguments']

    App\Repository\:
        resource: '../src/Repository'
        tags: ['repository.service_arguments']
        

    # add more service definitions when explicit configuration is needed
    # please note that last definitions always *replace* previous ones
